import { describe, expect, it } from 'vitest';
import type { LayoutInput, LayoutResult, ResolvedThemeMetricsView } from '../../../layout-api/src/contract.js';
import { createWorkerHost } from '../../../layout-api/src/host.js';
// @ts-expect-error -- generated by bench/generate-grid-fixture.js (gitignored;
// `pnpm generate:grid-fixture` writes it before this project runs).
import fixture from '../../../../bench/grid-fixture.json';

/**
 * DD-12 §12 item 3 (feat/b5-fixed): the real `fixedEngine`, through the real
 * `createWorkerHost`, inside a real `Worker` (`fixed.worker.ts`), against the
 * `LayoutResult` Node computed for the same input with the same sequence
 * (`bench/generate-grid-fixture.js`). `bitwise` (N17): the browser's output
 * must equal Node's byte for byte, and two runs must equal each other. The
 * cases: every node pinned (`forty-three-pinned`), half pinned, whose two
 * SGL4020 notes come back as diagnostics (`pin-half`), and ports on
 * unpinned nodes (`ports`).
 */

interface Case {
  readonly input: LayoutInput;
  readonly expected: LayoutResult;
}
const { metrics, fixed } = fixture as { readonly metrics: ResolvedThemeMetricsView; readonly fixed: Readonly<Record<string, Case>> };

const UNPINNED: Readonly<Record<string, number>> = { 'layout/forty-three-pinned.sgl': 0, 'layout/pin-half.sgl': 2, 'ports.sgl': 5 };

const spawn = (): Worker => new Worker(new URL('./fixed.worker.ts', import.meta.url), { type: 'module' });
/** Generous, as in grid.browser.test.ts: a cold Vite cache under a busy
 *  unit project can push the first request (which includes the worker's
 *  module load) past the 2 s production timeout. */
const createHost = () => createWorkerHost(spawn, { engineTimeoutMs: { 'sgl.fixed': 30_000 } });
const run = (host: ReturnType<typeof createHost>, input: LayoutInput) => host.run('sgl.fixed', input, {}, metrics, {}, new AbortController().signal);

describe('sgl.fixed through a real Worker (DD-12 §12 item 3)', () => {
  it('has the three cases', () => {
    expect(Object.keys(fixed).sort()).toEqual(['layout/forty-three-pinned.sgl', 'layout/pin-half.sgl', 'ports.sgl']);
  });

  for (const [name, { input, expected }] of Object.entries(fixed)) {
    it(`${name}: matches the Node-computed result bitwise, twice`, async () => {
      const host = createHost();
      try {
        const first = await run(host, input);
        const second = await run(host, input);
        expect(first.value).not.toBeNull();
        expect(JSON.stringify(first.value)).toBe(JSON.stringify(expected));
        expect(JSON.stringify(second.value)).toBe(JSON.stringify(first.value));
        const codes = first.diagnostics.map((d) => d.code);
        // One SGL4020 per unpinned node: none, two, and all five of ports.sgl's.
        expect(codes).toEqual(new Array<string>(UNPINNED[name] ?? -1).fill('SGL4020'));
      } finally {
        host.dispose();
      }
    });
  }
});
