import { describe, expect, it } from 'vitest';
import type { LayoutInput, LayoutResult, ResolvedThemeMetricsView } from '../../../layout-api/src/contract.js';
import { createWorkerHost } from '../../../layout-api/src/host.js';
// @ts-expect-error -- generated by bench/generate-grid-fixture.js (gitignored;
// `pnpm generate:grid-fixture` writes it before this project runs), not a
// source file this package ships or type-checks against.
import fixture from '../../../../bench/grid-fixture.json';

/**
 * The real `gridEngine`, run through the real `createWorkerHost`, inside a
 * real `Worker`. `grid.worker.ts` is the dedicated worker entry;
 * `bench/generate-grid-fixture.js` precomputes both the `LayoutInput` and the
 * **expected** `LayoutResult` in Node, off a real corpus document (`n50.sgl`,
 * Gate 1's "no stage hand-builds a SemanticGraph"), by running the exact
 * sequence `host.ts`/`worker-runtime.ts` run for a real request
 * (`gridEngine.layout -> routeStraight -> placeLabels -> quantize(…, 64)`).
 *
 * `vitest.config.ts`'s `browser` project runs this file once per browser
 * instance (Chromium, Firefox). Stage H fix round 1 only asserted a
 * same-browser double-run, which proves determinism *within* each browser but
 * never compares one browser's output to another's, let alone to Node's —
 * not what DD-06 §10's "bitwise double-run across Chrome and Firefox" means.
 * Comparing each browser's own output against the Node-computed `expected`
 * (fix round 2, item 1) is what actually proves Node ≡ Chromium ≡ Firefox.
 */

interface Fixture {
  readonly input: LayoutInput;
  readonly metrics: ResolvedThemeMetricsView;
  readonly expected: LayoutResult;
}

const { input, metrics, expected } = fixture as Fixture;

function spawn(): Worker {
  return new Worker(new URL('./grid.worker.ts', import.meta.url), { type: 'module' });
}

/** These tests prove bitwise equality, not `sgl.grid`'s 2 s production timeout
 *  (`DEFAULT_ENGINE_TIMEOUT_MS`, covered by the host's own tests). A request's
 *  timer includes the worker's first module load, which on a cold Vite cache
 *  (`pnpm check` from clean) also pays dependency optimisation while the Node
 *  unit project saturates the CPU. That repeatedly pushed the first request past
 *  2 s and failed with `SGL4001`, so the timeout here is generous. */
const createHost = () => createWorkerHost(spawn, { engineTimeoutMs: { 'sgl.grid': 30_000 } });

describe('sgl.grid through a real Worker (DD-06 §10)', () => {
  it('matches the Node-computed expected result bitwise — proves Node ≡ this browser', async () => {
    const host = createHost();
    try {
      const outcome = await host.run('sgl.grid', input, {}, metrics, {}, new AbortController().signal);
      expect(outcome.diagnostics).toEqual([]);
      expect(outcome.value).not.toBeNull();
      expect(Object.keys(outcome.value?.nodes ?? {}).length).toBeGreaterThan(0);
      // If this genuinely differs across environments, that is an ADR-0004
      // finding to report, not an assertion to loosen.
      expect(JSON.stringify(outcome.value)).toBe(JSON.stringify(expected));
    } finally {
      host.dispose();
    }
  });

  it('is bitwise-identical across two runs (ADR-0004, DD-06 §10)', async () => {
    const host = createHost();
    try {
      const first = await host.run('sgl.grid', input, {}, metrics, {}, new AbortController().signal);
      const second = await host.run('sgl.grid', input, {}, metrics, {}, new AbortController().signal);
      expect(first.value).not.toBeNull();
      expect(JSON.stringify(second.value)).toBe(JSON.stringify(first.value));
    } finally {
      host.dispose();
    }
  });
});
