import { describe, expect, it } from 'vitest';
import type { LayoutInput, ResolvedThemeMetricsView } from '../../../layout-api/src/contract.js';
import { createWorkerHost } from '../../../layout-api/src/host.js';
// @ts-expect-error -- generated by bench/generate-grid-fixture.js (gitignored;
// `pnpm generate:grid-fixture` writes it before this project runs), not a
// source file this package ships or type-checks against.
import fixture from '../../../../bench/grid-fixture.json';

/**
 * Stage H fix round 1, item 3: the real `gridEngine`, run through the real
 * `createWorkerHost`, inside a real `Worker`, in Chromium and Firefox
 * (`vitest.config.ts`'s `browser` project runs every `*.browser.test.ts` file
 * once per browser instance already, so "cross-browser" needs nothing extra
 * beyond this one file). `grid.worker.ts` is the dedicated worker entry;
 * `bench/generate-grid-fixture.js` precomputes the `LayoutInput` in Node, off
 * a real corpus document (`n50.sgl`), the same way Gate 1's "no stage
 * hand-builds a SemanticGraph" rule is honoured everywhere else.
 */

interface Fixture {
  readonly input: LayoutInput;
  readonly metrics: ResolvedThemeMetricsView;
}

const { input, metrics } = fixture as Fixture;

function spawn(): Worker {
  return new Worker(new URL('./grid.worker.ts', import.meta.url), { type: 'module' });
}

describe('sgl.grid through a real Worker (Stage H fix round 1, item 3)', () => {
  it('produces a valid, non-null LayoutResult for a corpus-derived LayoutInput', async () => {
    const host = createWorkerHost(spawn);
    try {
      const outcome = await host.run('sgl.grid', input, {}, metrics, {}, new AbortController().signal);
      expect(outcome.diagnostics).toEqual([]);
      expect(outcome.value).not.toBeNull();
      expect(Object.keys(outcome.value?.nodes ?? {}).length).toBeGreaterThan(0);
    } finally {
      host.dispose();
    }
  });

  it('is bitwise-identical across two runs (ADR-0004, DD-06 §10)', async () => {
    const host = createWorkerHost(spawn);
    try {
      const first = await host.run('sgl.grid', input, {}, metrics, {}, new AbortController().signal);
      const second = await host.run('sgl.grid', input, {}, metrics, {}, new AbortController().signal);
      expect(first.value).not.toBeNull();
      expect(JSON.stringify(second.value)).toBe(JSON.stringify(first.value));
    } finally {
      host.dispose();
    }
  });
});
