import { describe, expect, it } from 'vitest';
import type { LayoutInput, LayoutResult, ResolvedThemeMetricsView } from '../../../layout-api/src/contract.js';
import { createWorkerHost } from '../../../layout-api/src/host.js';
// @ts-expect-error -- generated by bench/generate-grid-fixture.js (gitignored;
// `pnpm generate:grid-fixture` writes it before this project runs).
import fixture from '../../../../bench/grid-fixture.json';

/**
 * DD-12 §12 item 3 (feat/b5-radial): `radial` is `bitwise` (N44, H8: its own
 * `sinTurn`/`cosTurn`, never `Math.sin`/`Math.cos`), so Chromium's output
 * must equal Node's byte for byte, as `tree.browser.test.ts` checks for
 * `tree`:
 *
 * - through the real `createWorkerHost`, inside a real `Worker`
 *   (`radial.worker.ts`), whose `radialEngine` loads the `std-trees` chunk
 *   on its first request: the quantized result, twice, against the one Node
 *   computed with the same sequence (`bench/generate-grid-fixture.js`);
 * - and the engine's raw output, computed inside that worker, against
 *   Node's raw output, so the equality is not quantization absorbing a
 *   last-bit difference.
 *
 * The cases: nested containers (`tree-direction`), a forest of discs
 * (`tree-forest`), the 40-node criterion-1 document, `n50`, and
 * `mixed-widths`, a generated 60-node tree of 1–3 or 30–50 character labels,
 * so its wedges are uneven fractions of a turn and nearly every angle is a
 * different one.
 */

interface Case {
  readonly input: LayoutInput;
  readonly raw: LayoutResult;
  readonly expected: LayoutResult;
}
const { metrics, radial } = fixture as { readonly metrics: ResolvedThemeMetricsView; readonly radial: Readonly<Record<string, Case>> };

const spawn = (): Worker => new Worker(new URL('./radial.worker.ts', import.meta.url), { type: 'module' });
/** Generous, as in tree.browser.test.ts: a cold Vite cache can push the
 *  first request past the 5 s production timeout. */
const createHost = () => createWorkerHost(spawn, { engineTimeoutMs: { 'sgl.radial': 30_000 } });
const run = (host: ReturnType<typeof createHost>, input: LayoutInput) => host.run('sgl.radial', input, {}, metrics, {}, new AbortController().signal);

/** The engine's raw output for `input`, computed inside a fresh worker. */
function rawInWorker(input: LayoutInput): Promise<string> {
  const worker = spawn();
  return new Promise<string>((resolve, reject) => {
    worker.addEventListener('message', (ev: MessageEvent<{ t: string; json?: string }>) => {
      if (ev.data.t === 'raw-radial' && ev.data.json !== undefined) resolve(ev.data.json);
    });
    worker.addEventListener('error', (ev) => reject(new Error(ev.message)));
    worker.postMessage({ t: 'raw-radial', input, metrics });
  }).finally(() => worker.terminate());
}

describe('sgl.radial in Chromium equals Node, bitwise (DD-12 §12 item 3, N44)', () => {
  it('has the five cases', () => {
    expect(Object.keys(radial ?? {}).sort()).toEqual(['forty-three-level.sgl', 'layout/tree-direction.sgl', 'layout/tree-forest.sgl', 'mixed-widths', 'n50.sgl']);
  });

  for (const [name, { input, raw, expected }] of Object.entries(radial ?? {})) {
    it(`${name}: through a real Worker, the Node-computed result, twice`, async () => {
      const host = createHost();
      try {
        const first = await run(host, input);
        const second = await run(host, input);
        expect(first.diagnostics).toEqual([]);
        expect(first.value).not.toBeNull();
        expect(JSON.stringify(first.value)).toBe(JSON.stringify(expected));
        expect(JSON.stringify(second.value)).toBe(JSON.stringify(first.value));
      } finally {
        host.dispose();
      }
    });

    it(`${name}: the raw engine output, inside a real Worker, equals Node's`, async () => {
      const [a, b] = await Promise.all([rawInWorker(input), rawInWorker(input)]);
      expect(a).toBe(JSON.stringify(raw));
      expect(b).toBe(a);
    });
  }
});
