import { describe, expect, it } from 'vitest';
import type { LayoutContext, LayoutInput, LayoutResult, ResolvedThemeMetricsView } from '../../../layout-api/src/contract.js';
import { createWorkerHost } from '../../../layout-api/src/host.js';
import { treeEngine } from '../../src/lazy.js';
// @ts-expect-error -- generated by bench/generate-grid-fixture.js (gitignored;
// `pnpm generate:grid-fixture` writes it before this project runs).
import fixture from '../../../../bench/grid-fixture.json';

/**
 * DD-12 §12 item 3 (feat/b5-tree): `tree` is `bitwise` (N33), so Chromium's
 * output must equal Node's byte for byte:
 *
 * - through the real `createWorkerHost`, inside a real `Worker`
 *   (`tree.worker.ts`), whose `treeEngine` loads the `std-trees` chunk on its
 *   first request: the quantized result, twice, against the one Node computed
 *   with the same sequence (`bench/generate-grid-fixture.js`);
 * - and the engine's raw output, run here on the page, against Node's raw
 *   output, so the equality is not only quantization absorbing a difference.
 */

interface Case {
  readonly input: LayoutInput;
  readonly raw: LayoutResult;
  readonly expected: LayoutResult;
}
const { metrics, tree } = fixture as { readonly metrics: ResolvedThemeMetricsView; readonly tree: Readonly<Record<string, Case>> };

const spawn = (): Worker => new Worker(new URL('./tree.worker.ts', import.meta.url), { type: 'module' });
/** Generous, as in grid.browser.test.ts: a cold Vite cache under a busy
 *  project can push the first request (the worker's module load and the
 *  chunk's import) past the 5 s production timeout. */
const createHost = () => createWorkerHost(spawn, { engineTimeoutMs: { 'sgl.tree': 30_000 } });
const run = (host: ReturnType<typeof createHost>, input: LayoutInput) => host.run('sgl.tree', input, {}, metrics, {}, new AbortController().signal);

const ctx = {
  options: {},
  metrics,
  measure: {},
  random: () => 0,
  signal: new AbortController().signal,
  log: () => {},
} as unknown as LayoutContext;

describe('sgl.tree in Chromium equals Node, bitwise (DD-12 §12 item 3, N33)', () => {
  it('has the four cases', () => {
    expect(Object.keys(tree).sort()).toEqual(['forty-three-level.sgl', 'layout/tree-diamond.sgl', 'layout/tree-direction.sgl', 'n50.sgl']);
  });

  for (const [name, { input, raw, expected }] of Object.entries(tree)) {
    it(`${name}: through a real Worker, the Node-computed result, twice`, async () => {
      const host = createHost();
      try {
        const first = await run(host, input);
        const second = await run(host, input);
        expect(first.diagnostics).toEqual([]);
        expect(first.value).not.toBeNull();
        expect(JSON.stringify(first.value)).toBe(JSON.stringify(expected));
        expect(JSON.stringify(second.value)).toBe(JSON.stringify(first.value));
      } finally {
        host.dispose();
      }
    });

    it(`${name}: the raw engine output, on this page, equals Node's`, async () => {
      const a = await treeEngine.layout(input, ctx);
      const b = await treeEngine.layout(input, ctx);
      expect(JSON.stringify(a)).toBe(JSON.stringify(raw));
      expect(JSON.stringify(b)).toBe(JSON.stringify(a));
    });
  }
});
