// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_Identifier = {__proto__:null,true:100, false:100, null:102}
export const parser = LRParser.deserialize({
  version: 14,
  states: ")xQtQPOOO{QPO'#CdOOQO'#DX'#DXO!QQPO'#CvO!`QPO'#CzOOQO'#Cy'#CyO#WQPO'#CvO!QQPO'#CvO$OQPO'#CuO$sQPO'#CtO$xQPO'#DQOOQO'#Cc'#CcOOQO'#DU'#DUQ`QPOOO%gQPO'#CbQOQPOOO%nQPO,59OOOQO-E7V-E7VOOQO'#Cz'#CzO&VQPO,59bO&}QPO'#DYO&VQPO,59bO!QQPO,59bO'YQPO'#C}OOQO,59a,59aO'_QPO'#DZO'pQPO,59`O(bQPO,59lOOQO-E7S-E7SO(mQPO,58|OOQO,58|,58|OOQO'#Cj'#CjOOQO'#Cl'#ClOOQO'#Cm'#CmO(tQPO'#CpO({QPO'#CqOOQO'#Cg'#CgOOQO1G.j1G.jO)ZQPO1G.|OOQO,59t,59tOOQO-E7W-E7WO)ZQPO1G.|O*RQPO,59iOOQO,59u,59uOOQO-E7X-E7XO*WQPO1G.zOOQO'#DT'#DTOOQO'#DS'#DSOOQO1G/W1G/WOOQO1G.h1G.hOOQO'#DV'#DVO*`QPO,59[OOQO,59[,59[OOQO'#Cs'#CsO*gQPO'#CrOOQO'#DW'#DWO*lQPO,59]OOQO,59],59]O*zQPO7+$hOOQO1G/T1G/TOOQO'#DP'#DPOOQO7+$f7+$fOOQO-E7T-E7TOOQO1G.v1G.vO%nQPO,59^OOQO-E7U-E7UOOQO1G.w1G.wOOQO1G.x1G.x",
  stateData: "+z~O!QOSPOSQOS!ROS~OXPO[SO_SOkVOlQOoTO~OT^O~P`OY`O~O[bO_bOlQOoTO~OXuXYuX[uX_uXcnXkuXluXouXpnXrnX!OuXSuX~OpdOcjXrjXXjXYjX[jX_jXkjXljXojX!OjXSjX~OcgOriXXiXYiX[iX_iXkiXliXoiX!OiXSiX~OriO~OYkOXtX[tX_tXktXltXotX!OtXStX~OSnO~P`OTsO[tO]tO_qOcrO!SoO!TpO~OpdOcjarjaXjaYja[ja_jakjaljaoja!OjaSja~O[bO_bOoTO~O_zO~O[bO_bOkVOlQOoTO~OY}OriOXha[ha_hakhalhaoha!OhaSha~OT^O[!PO_!OO~OS!RO~P`Ob!UO~P%nOS!ZOX!VO[!VO_!VO~OpdOcjirjiXjiYji[ji_jikjiljioji!OjiSji~Ob!]O~OT^O[!^O~Ob!aO~P%nOY!bO~OS!dOX!VO[!VO_!VO~OpdOcjqrjqXjqYjq[jq_jqkjqljqojq!OjqSjq~OPQo_lkp~",
  goto: "%j!OPPPPPP!P!Y!`PP!fPP!pP!p!pPP!p!p!v!z!`#O#XPP#`#qPP#|P$P!`$S$Y$]$`$j$p$v%U%dQ_OQ!PkR!^}X[O]^mXZO]^mQu`S!Sr!TR!e!bXt`r!T!bT!Xs!YT!Ws!YWXO]^mR{iZWO]^imYUO]^imScRVQwdRyfcTORV]^dfimRhWR!_}XYO]^mR!QkR!PkQ]OSl]mRm^Q!TrR!`!TQ!YsR!c!YYRO]^imSaRfRfVQeUQvcUxev![R![yQjXR|j",
  nodeNames: "⚠ LineComment BlockComment Document } { Block Entry ConfigEntry ConfigKey : Value String Number Bool Identifier Null Word ] [ Array Object Property PropKey EdgeStmt Endpoint Path Root Parent PathStep PathSegment Wildcard . Port EdgeOp EdgeValue NodeDecl NodeKey NodeValue ClassRef",
  maxTerm: 51,
  nodeProps: [
    ["openedBy", 4,"{",18,"["],
    ["closedBy", 5,"}",19,"]"]
  ],
  skippedNodes: [0,1,2],
  repeatNodeCount: 6,
  tokenData: "-d~RkX^!vpq!vrs#kz{%_|}&s}!O&x!O!P't!P!Q(X!Q!['Z![!]*S!^!_*X!b!c*g!c!}+k!}#O-O#P#Q-T#R#S+k#T#o+k#o#p-Y#q#r-_#y#z!v$f$g!v#BY#BZ!v$IS$I_!v$I|$JO!v$JT$JU!v$KV$KW!v&FU&FV!v~!{Y!Q~X^!vpq!v#y#z!v$f$g!v#BY#BZ!v$IS$I_!v$I|$JO!v$JT$JU!v$KV$KW!v&FU&FV!v~#nWOY#kZr#krs$Ws#O#k#O#P$]#P;'S#k;'S;=`%X<%lO#k~$]O[~~$`RO;'S#k;'S;=`$i;=`O#k~$lXOY#kZr#krs$Ws#O#k#O#P$]#P;'S#k;'S;=`%X;=`<%l#k<%lO#k~%[P;=`<%l#k~%dUo~z{%v}!O%{!Q![&_!c!}&_#R#S&_#T#o&_~%{Oo~~&OT}!O%{!Q![&_!c!}&_#R#S&_#T#o&_~&dTo~}!O%{!Q![&_!c!}&_#R#S&_#T#o&_~&xO!R~~&{R}!O'U!Q!['Z!`!a'U~'ZOr~~'`Q]~!O!P'f!Q!['Z~'iP!Q!['l~'qP]~!Q!['l~'yPp~!O!P'|~(PP!P!Q(S~(XOl~~(^Qk~z{(d!P!Q)k~(gTOz(dz{(v{;'S(d;'S;=`)e<%lO(d~(yVOz(dz{(v{!P(d!P!Q)`!Q;'S(d;'S;=`)e<%lO(d~)eOQ~~)hP;=`<%l(d~)pSP~OY)kZ;'S)k;'S;=`)|<%lO)k~*PP;=`<%l)k~*XOY~~*[P}!O*_~*dPr~!`!a'U~*jR!c!}*s#R#S*s#T#o*s~*xUX~}!O+[!O!P*g!Q![*s!c!}*s#R#S*s#T#o*s~+_S!Q![*s!c!}*s#R#S*s#T#o*s~+pU_~z{&_}!O,S!Q![+k!c!}+k#R#S+k#T#o+k~,VUz{&_}!O,i!Q![+k!c!}+k#R#S+k#T#o+k~,lUz{&_}!O,i!Q![,i!c!},i#R#S,i#T#o,i~-TOc~~-YOb~~-_OT~~-dOS~",
  tokenizers: [0],
  topRules: {"Document":[0,3]},
  specialized: [{term: 15, get: (value) => spec_Identifier[value] || -1}],
  tokenPrec: 494
})
