// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_Identifier = {__proto__:null,true:104, false:104, null:106}
export const parser = LRParser.deserialize({
  version: 14,
  states: ")xQwQPOOO!OQPO'#CdOOQO'#DZ'#DZO!TQPO'#CxO!cQPO'#C|OOQO'#C{'#C{O#^QPO'#CxO!TQPO'#CxO$XQPO'#CwO%PQPO'#CvO%UQPO'#DSOOQO'#Cc'#CcOOQO'#DW'#DWQ`QPOOO%vQPO'#CbQOQPOOO%}QPO,59OOOQO-E7X-E7XOOQO'#C|'#C|O&lQPO,59dO'gQPO'#D[O&lQPO,59dO!TQPO,59dO'rQPO'#DPOOQO,59c,59cO'wQPO'#D]O(YQPO,59bO(}QPO,59nOOQO-E7U-E7UO)]QPO,58|OOQO,58|,58|OOQO'#Ck'#CkOOQO'#Cm'#CmOOQO'#Cn'#CnO)dQPO'#CrO)kQPO'#CsOOQO'#Ch'#ChOOQO1G.j1G.jO)|QPO1G/OOOQO,59v,59vOOQO-E7Y-E7YO)|QPO1G/OO*wQPO,59kOOQO,59w,59wOOQO-E7Z-E7ZO*|QPO1G.|OOQO'#DV'#DVOOQO'#DU'#DUOOQO1G/Y1G/YOOQO1G.h1G.hOOQO'#DX'#DXO+XQPO,59^OOQO,59^,59^OOQO'#Cu'#CuO+`QPO'#CtOOQO'#DY'#DYO+eQPO,59_OOQO,59_,59_O+vQPO7+$jOOQO1G/V1G/VOOQO'#DR'#DROOQO7+$h7+$hOOQO-E7V-E7VOOQO1G.x1G.xO%}QPO,59`OOQO-E7W-E7WOOQO1G.y1G.yOOQO1G.z1G.z",
  stateData: ",{~O!SOSPOSQOS!TOS~OXPOYPO]SO`SOmVOnQOqTO~OT^O~P`OZ`O~O]bO`bOnQOqTO~OXwXYwXZwX]wX`wXepXmwXnwXqwXrpXtpX!QwXSwX~OrdOelXtlXXlXYlXZlX]lX`lXmlXnlXqlX!QlXSlX~OegOtkXXkXYkXZkX]kX`kXmkXnkXqkX!QkXSkX~OtiO~OZkOXvXYvX]vX`vXmvXnvXqvX!QvXSvX~OSnO~P`OTsOYtO]tO^tO`qOctOerO!UoO!VpO~OrdOelatlaXlaYlaZla]la`lamlanlaqla!QlaSla~O]bO`bOqTO~O`zO~O]bO`bOmVOnQOqTO~OZ}OtiOXjaYja]ja`jamjanjaqja!QjaSja~OT^OY!PO]!PO`!OO~OS!RO~P`Od!UO~P%}OS!ZOX!VOY!VO]!VO`!VO~OrdOelitliXliYliZli]li`limlinliqli!QliSli~Od!]O~OT^OY!^O]!^O~Od!aO~P%}OZ!bO~OS!dOX!VOY!VO]!VO`!VO~OrdOelqtlqXlqYlqZlq]lq`lqmlqnlqqlq!QlqSlq~OPQY]q`nrm~",
  goto: "%l!QPPPPPP!R![!bPPP!hPP!rP!r!rPPP!r!r!x!|!b#Q#ZPP#b#sPP$OP$R!b$U$[$_$b$l$r$x%W%fQ_OQ!PkR!^}X[O]^mXZO]^mQu`S!Sr!TR!e!bXt`r!T!bT!Xs!YT!Ws!YWXO]^mR{iZWO]^imYUO]^imScRVQwdRyfcTORV]^dfimRhWR!_}XYO]^mR!QkR!PkQ]OSl]mRm^Q!TrR!`!TQ!YsR!c!YYRO]^imSaRfRfVQeUQvcUxev![R![yQjXR|j",
  nodeNames: "⚠ LineComment BlockComment Document } { Block Entry ConfigEntry ConfigKey ConfigString : Value String Number Bool Identifier Null Word Variable ] [ Array Object Property PropKey EdgeStmt Endpoint Path Root Parent PathStep PathSegment Wildcard . Port EdgeOp EdgeValue NodeDecl NodeKey NodeValue ClassRef",
  maxTerm: 53,
  nodeProps: [
    ["openedBy", 4,"{",20,"["],
    ["closedBy", 5,"}",21,"]"]
  ],
  skippedNodes: [0,1,2],
  repeatNodeCount: 6,
  tokenData: "1P~RlX^!ypq!yrs#ntu'yz{(z|}*`}!O*e!O!P+a!P!Q+t!Q![*v![!]-o!^!_-t!b!c.S!c!}/W!}#O0k#P#Q0p#R#S/W#T#o/W#o#p0u#q#r0z#y#z!y$f$g!y#BY#BZ!y$IS$I_!y$I|$JO!y$JT$JU!y$KV$KW!y&FU&FV!y~#OY!S~X^!ypq!y#y#z!y$f$g!y#BY#BZ!y$IS$I_!y$I|$JO!y$JT$JU!y$KV$KW!y&FU&FV!y~#qYOY$aZr$ars$|s!b$a!b!c&T!c#O$a#O#P%R#P;'S$a;'S;=`%}<%lO$a~$dWOY$aZr$ars$|s#O$a#O#P%R#P;'S$a;'S;=`%}<%lO$a~%RO]~~%URO;'S$a;'S;=`%_;=`O$a~%bXOY$aZr$ars$|s#O$a#O#P%R#P;'S$a;'S;=`%};=`<%l$a<%lO$a~&QP;=`<%l$a~&WWOY&TZr&Trs&ps#O&T#O#P&w#P;'S&T;'S;=`'s<%lO&T~&wOY~]~~&zRO;'S&T;'S;=`'T;=`O&T~'WXOY&TZr&Trs&ps#O&T#O#P&w#P;'S&T;'S;=`'s;=`<%l&T<%lO&T~'vP;=`<%l&T~'|R!c!}(V#R#S(V#T#o(V~([Tc~}!O(k!Q![(V!c!}(V#R#S(V#T#o(V~(nS!Q![(V!c!}(V#R#S(V#T#o(V~)PUq~z{)c}!O)h!Q![)z!c!})z#R#S)z#T#o)z~)hOq~~)kT}!O)h!Q![)z!c!})z#R#S)z#T#o)z~*PTq~}!O)h!Q![)z!c!})z#R#S)z#T#o)z~*eO!T~~*hR}!O*q!Q![*v!`!a*q~*vOt~~*{Q^~!O!P+R!Q![*v~+UP!Q![+X~+^P^~!Q![+X~+fPr~!O!P+i~+lP!P!Q+o~+tOn~~+yQm~z{,P!P!Q-W~,STOz,Pz{,c{;'S,P;'S;=`-Q<%lO,P~,fVOz,Pz{,c{!P,P!P!Q,{!Q;'S,P;'S;=`-Q<%lO,P~-QOQ~~-TP;=`<%l,P~-]SP~OY-WZ;'S-W;'S;=`-i<%lO-W~-lP;=`<%l-W~-tOZ~~-wP}!O-z~.PPt~!`!a*q~.VR!c!}.`#R#S.`#T#o.`~.eUX~}!O.w!O!P.S!Q![.`!c!}.`#R#S.`#T#o.`~.zS!Q![.`!c!}.`#R#S.`#T#o.`~/]U`~z{)z}!O/o!Q![/W!c!}/W#R#S/W#T#o/W~/rUz{)z}!O0U!Q![/W!c!}/W#R#S/W#T#o/W~0XUz{)z}!O0U!Q![0U!c!}0U#R#S0U#T#o0U~0pOe~~0uOd~~0zOT~~1POS~",
  tokenizers: [0],
  topRules: {"Document":[0,3]},
  specialized: [{term: 16, get: (value) => spec_Identifier[value] || -1}],
  tokenPrec: 539
})
