// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_Identifier = {__proto__:null,true:106, false:106, null:108}
export const parser = LRParser.deserialize({
  version: 14,
  states: "*hQwQPOOO!OQPO'#CdOOQO'#D['#D[O!TQPO'#CyO!cQPO'#C}OOQO'#C|'#C|O#^QPO'#CyO!TQPO'#CyO$XQPO'#CxO%PQPO'#CwO%UQPO'#DSOOQO'#Cc'#CcOOQO'#DW'#DWQ`QPOOO%vQPO'#CbQOQPOOO%}QPO,59OOOQO-E7Y-E7YOOQO'#C}'#C}O&lQPO,59eO'gQPO'#D]O&lQPO,59eO!TQPO,59eO'rQPO'#DPOOQO,59d,59dO'wQPO'#D^O(YQPO,59cO(}QPO,59nOOQO-E7U-E7UO)]QPO,58|OOQO,58|,58|OOQO'#Ck'#CkOOQO'#Cm'#CmO)dQPO'#DeOOQO'#Cn'#CnO*kQPO'#CsO*rQPO'#CtOOQO'#Ch'#ChOOQO1G.j1G.jO+TQPO1G/POOQO,59w,59wOOQO-E7Z-E7ZO+TQPO1G/PO,OQPO,59kOOQO,59x,59xOOQO-E7[-E7[O,TQPO1G.}OOQO'#DV'#DVOOQO'#DU'#DUOOQO1G/Y1G/YOOQO1G.h1G.hO,`QPO'#DXO,eQPO,5:POOQO'#DY'#DYO-lQPO,59_OOQO,59_,59_OOQO'#Cv'#CvO-sQPO'#CuOOQO'#DZ'#DZO-xQPO,59`OOQO,59`,59`O.ZQPO7+$kOOQO1G/V1G/VOOQO'#DR'#DROOQO7+$i7+$iOOQO,59s,59sOOQO-E7V-E7VOOQO-E7W-E7WOOQO1G.y1G.yO%}QPO,59aOOQO-E7X-E7XOOQO1G.z1G.zOOQO1G.{1G.{",
  stateData: "/`~O!TOSPOSQOS!UOS~OXPOYPO]SO`SOnVOoQOrTO~OT^O~P`OZ`O~O]bO`bOoQOrTO~OXwXYwXZwX]wX`wXcqXfqXnwXowXrwXtqX!RwXSwX~OcdOfmXtmXXmXYmXZmX]mX`mXnmXomXrmX!RmXSmX~OfgOtlXXlXYlXZlX]lX`lXnlXolXrlX!RlXSlX~OtiO~OZkOXvXYvX]vX`vXnvXovXrvX!RvXSvX~OSnO~P`OTtOYuO]uO^uO`qOduOfsO!VoO!WpO~OcdOfmatmaXmaYmaZma]ma`manmaomarma!RmaSma~O]bO`bOrTO~O`{O~O]bO`bOnVOoQOrTO~OZ!OOtiOXkaYka]ka`kankaokarka!RkaSka~OT^OY!QO]!QO`qO~OS!SO~P`Oc!TOX!XXY!XX]!XX`!XXn!XXo!XXr!XX!R!XXT!XX^!XXd!XXe!XXf!XX!V!XX!W!XXS!XX~Oe!XO~P%}OS!^OX!YOY!YO]!YO`!YO~OcdOfmitmiXmiYmiZmi]mi`minmiomirmi!RmiSmi~Oe!`O~OT^OY!aO]!aO~O`!cO~Oc!TOX!XaY!Xa]!Xa`!Xan!Xao!Xar!Xa!R!XaT!Xa^!Xad!Xae!Xaf!Xa!V!Xa!W!XaS!Xa~Oe!fO~P%}OZ!gO~OS!iOX!YOY!YO]!YO`!YO~OcdOfmqtmqXmqYmqZmq]mq`mqnmqomqrmq!RmqSmq~OPQY]r`ocn~",
  goto: "&T!YPPPPPP!Z!d!jPPP!pPP!zP!z!zPPPP!z!z#Q#U!j#Y#cPP#j#{P$WP$Z!j$^$d$g$j$t$z%Q%W%f%tPPPPPP%zQ_OQ!QkR!a!OX[O]^mXZO]^mQv`S!Vs!WR!j!gXu`s!W!gT![t!]T!Zt!]WXO]^mR|iZWO]^imYUO]^imScRVQxdRzfcTORV]^dfimRhWR!b!OXYO]^mR!RkR!QkQ]OSl]mRm^Q!UqR!d!UQ!WsR!e!WQ!]tR!h!]YRO]^imSaRfRfVQeUQwcUyew!_R!_zQjXR}jWr`s!W!gR!Pk",
  nodeNames: "⚠ LineComment BlockComment Document } { Block Entry ConfigEntry ConfigKey ConfigString : Value String Number Bool Identifier Null Word . Variable ] [ Array Object Property PropKey EdgeStmt Endpoint Path Root Parent PathStep PathSegment Wildcard Port EdgeOp EdgeValue NodeDecl NodeKey NodeValue ClassRef",
  maxTerm: 55,
  nodeProps: [
    ["openedBy", 4,"{",21,"["],
    ["closedBy", 5,"}",22,"]"]
  ],
  skippedNodes: [0,1,2],
  repeatNodeCount: 7,
  tokenData: "1S~RlX^!ypq!yrs#ntu'yz{(}|}*c}!O*h!O!P+d!P!Q+w!Q![*y![!]-r!^!_-w!b!c.V!c!}/Z!}#O0n#P#Q0s#R#S/Z#T#o/Z#o#p0x#q#r0}#y#z!y$f$g!y#BY#BZ!y$IS$I_!y$I|$JO!y$JT$JU!y$KV$KW!y&FU&FV!y~#OY!T~X^!ypq!y#y#z!y$f$g!y#BY#BZ!y$IS$I_!y$I|$JO!y$JT$JU!y$KV$KW!y&FU&FV!y~#qYOY$aZr$ars$|s!b$a!b!c&T!c#O$a#O#P%R#P;'S$a;'S;=`%}<%lO$a~$dWOY$aZr$ars$|s#O$a#O#P%R#P;'S$a;'S;=`%}<%lO$a~%RO]~~%URO;'S$a;'S;=`%_;=`O$a~%bXOY$aZr$ars$|s#O$a#O#P%R#P;'S$a;'S;=`%};=`<%l$a<%lO$a~&QP;=`<%l$a~&WWOY&TZr&Trs&ps#O&T#O#P&w#P;'S&T;'S;=`'s<%lO&T~&wOY~]~~&zRO;'S&T;'S;=`'T;=`O&T~'WXOY&TZr&Trs&ps#O&T#O#P&w#P;'S&T;'S;=`'s;=`<%l&T<%lO&T~'vP;=`<%l&T~'|R!c!}(V#R#S(V#T#o(V~([Ud~}!O(n!O!P'y!Q![(V!c!}(V#R#S(V#T#o(V~(qS!Q![(V!c!}(V#R#S(V#T#o(V~)SUr~z{)f}!O)k!Q![)}!c!})}#R#S)}#T#o)}~)kOr~~)nT}!O)k!Q![)}!c!})}#R#S)}#T#o)}~*STr~}!O)k!Q![)}!c!})}#R#S)}#T#o)}~*hO!U~~*kR}!O*t!Q![*y!`!a*t~*yOt~~+OQ^~!O!P+U!Q![*y~+XP!Q![+[~+aP^~!Q![+[~+iPc~!O!P+l~+oP!P!Q+r~+wOo~~+|Qn~z{,S!P!Q-Z~,VTOz,Sz{,f{;'S,S;'S;=`-T<%lO,S~,iVOz,Sz{,f{!P,S!P!Q-O!Q;'S,S;'S;=`-T<%lO,S~-TOQ~~-WP;=`<%l,S~-`SP~OY-ZZ;'S-Z;'S;=`-l<%lO-Z~-oP;=`<%l-Z~-wOZ~~-zP}!O-}~.SPt~!`!a*t~.YR!c!}.c#R#S.c#T#o.c~.hUX~}!O.z!O!P.V!Q![.c!c!}.c#R#S.c#T#o.c~.}S!Q![.c!c!}.c#R#S.c#T#o.c~/`U`~z{)}}!O/r!Q![/Z!c!}/Z#R#S/Z#T#o/Z~/uUz{)}}!O0X!Q![/Z!c!}/Z#R#S/Z#T#o/Z~0[Uz{)}}!O0X!Q![0X!c!}0X#R#S0X#T#o0X~0sOf~~0xOe~~0}OT~~1SOS~",
  tokenizers: [0],
  topRules: {"Document":[0,3]},
  specialized: [{term: 16, get: (value) => spec_Identifier[value] || -1}],
  tokenPrec: 650
})
