#!/usr/bin/env node
// Deterministically writes the generated scale fixtures the perf bench needs.
// No `Math.random`, no `Date.now` (DD-00 §3) — every byte here is a pure
// function of the node count, so re-running this script produces
// byte-identical output, which is what keeps these three out of source
// control (bench/README.md): the shape of a 2 000-node document is one
// decision, made here, not a diff to review each time it changes.
//
// Run with `node bench/generate.js`. Wired into `pnpm test`/`pnpm check` (root
// package.json) so the files always exist before Vitest collects `corpus/`.
//
// `corpus/unresolved/edge-expansion-limit.sgl` (the SGL3005 fixture) used to
// be generated here too, but it is a ~30-line correctness fixture, not a
// scale one — its shape is not "one decision to keep out of diffs" the way
// n50/n500/n2000's is, and generating it made a correctness gate depend on a
// build step running first (a bare `vitest run` or an IDE test runner outside
// `pnpm test` would ENOENT on it). It is committed as a plain corpus fixture
// instead, like every other `unresolved/*.sgl` document.

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const corpusDir = fileURLToPath(new URL('../corpus/', import.meta.url));

/**
 * A flat scale fixture: `n` nodes in a chain (`n0 -> n1 -> n2 -> ...`), grouped
 * into containers of 10 so a scale document also exercises nesting rather than
 * one 2 000-wide root. Every 7th node carries a label with a multi-word string,
 * so measurement is exercised too, not just node/edge count.
 */
function scaleDocument(n) {
  const perContainer = 10;
  const lines = [`// Generated by bench/generate.js — ${n} nodes. Do not hand-edit.`, `@title: "Scale ${n}"`, ''];

  const containerCount = Math.ceil(n / perContainer);
  let nodeIndex = 0;
  for (let c = 0; c < containerCount; c += 1) {
    lines.push(`g${c}: {`);
    const inThisContainer = Math.min(perContainer, n - nodeIndex);
    for (let i = 0; i < inThisContainer; i += 1) {
      const label = nodeIndex % 7 === 0 ? ` { @label: "Node number ${nodeIndex}" }` : ' {}';
      lines.push(`  n${nodeIndex}:${label}`);
      nodeIndex += 1;
    }
    lines.push('}');
  }

  lines.push('');
  for (let i = 0; i < n - 1; i += 1) {
    lines.push(`g${Math.floor(i / perContainer)}.n${i} -> g${Math.floor((i + 1) / perContainer)}.n${i + 1}`);
  }
  lines.push('');
  return lines.join('\n');
}

function write(relPath, content) {
  writeFileSync(`${corpusDir}${relPath}`, content, 'utf8');
}

write('n50.sgl', scaleDocument(50));
write('n500.sgl', scaleDocument(500));
write('n2000.sgl', scaleDocument(2000));

console.log('bench/generate.js: wrote n50.sgl, n500.sgl, n2000.sgl');
