import morphdom from 'morphdom';
import { afterAll, describe, expect, it, vi } from 'vitest';
import { canonicalise, fnv1a64 } from '@sgl/core';
import { styleGraph, type ComputedStyle } from '@sgl/theme';
import { fnv1a64Fast } from './f9-proto/fnv-fast.js';
import type { LayoutView } from '../../src/layout-view.js';
import { render } from '../../src/index.js';
import { renderInvariant, renderMainProto, renderPaintOnly } from './f9-proto/render-invariant.js';
// @ts-expect-error -- generated by bench/generate-render-fixtures.js (gitignored).
import fixtures from '../../../../bench/render-fixtures.json';

/**
 * F9 PHASE 1 (Stage L): measurement prototypes, not an asserting test.
 *
 * Times a real theme switch, neutral-light -> neutral-dark, on the canvas's
 * own DOM shape (`svg.host > g.viewport > g.rendered`, DD-08 §6), in
 * Chromium, with the forced layout (`wrapper.getBBox()`) inside the timed
 * region, as F9's budget requires. Every run starts from a freshly mounted,
 * laid-out light render (untimed), so each timed run is one genuine switch.
 *
 * Phases, separated by `performance.now()` (bench only):
 *   (a) building what the swap needs: `render()` (or the prototype's);
 *   (b) getting it into the DOM: `innerHTML`, or parse + morphdom, or the
 *       `<style>`/`<defs>` text swap;
 *   (c) `wrapper.getBBox()`: style recalculation + layout, forced now.
 *
 * Run alone (about 3 minutes; it skips itself in Firefox):
 *   PLAYWRIGHT_BROWSERS_PATH=/home/user/pw-browsers pnpm exec vitest run \
 *     --project 'browser (chromium)' packages/render-svg/test/browser/f9-phase1.bench.browser.test.ts
 * Every line is printed again under `[F9-P1] SUMMARY` at the end.
 */

interface Fixture {
  readonly doc: string;
  readonly themeName: string;
  readonly styled: Parameters<typeof render>[0];
  readonly result: LayoutView;
  readonly theme: Parameters<typeof render>[2];
}

const FIXTURES = fixtures as readonly Fixture[];
vi.setConfig({ testTimeout: 300_000 });
const RUNS = 21;
const WARMUP = 3;
const DOCS = ['n50.sgl', 'n500.sgl', 'n2000.sgl'] as const;
const IS_FIREFOX = navigator.userAgent.includes('Firefox');
const SVG_NS = 'http://www.w3.org/2000/svg';

function fixture(doc: string, themeName: string): Fixture {
  const f = FIXTURES.find((x) => x.doc === doc && x.themeName === themeName);
  if (f === undefined) throw new Error(`no fixture ${doc} / ${themeName}`);
  return f;
}

interface Sample {
  readonly a: number;
  readonly b: number;
  readonly c: number;
  readonly total: number;
}

function median(values: readonly number[]): number {
  const s = [...values].sort((x, y) => x - y);
  const m = Math.floor(s.length / 2);
  return s.length % 2 === 1 ? s[m]! : (s[m - 1]! + s[m]!) / 2;
}

function fmt(values: readonly number[]): string {
  return `${median(values).toFixed(2)} [${Math.min(...values).toFixed(2)}-${Math.max(...values).toFixed(2)}]`;
}

/** The canvas's DOM (DD-08 §6), attached so layout is real. */
function mount(): { host: SVGSVGElement; wrapper: SVGGElement } {
  const host = document.createElementNS(SVG_NS, 'svg');
  host.setAttribute('class', 'host');
  host.setAttribute('width', '1200');
  host.setAttribute('height', '800');
  const viewport = document.createElementNS(SVG_NS, 'g');
  viewport.setAttribute('class', 'viewport');
  const wrapper = document.createElementNS(SVG_NS, 'g');
  wrapper.setAttribute('class', 'rendered');
  viewport.appendChild(wrapper);
  host.appendChild(viewport);
  document.body.appendChild(host);
  return { host, wrapper };
}

type Switch = (wrapper: SVGGElement, t: number[]) => void;

/**
 * Runs `WARMUP + RUNS` switches. Before each: remount the light picture and
 * force its layout (untimed). `step` records `t[0..3]` at the phase edges.
 */
function bench(lightSvg: string, step: Switch): Sample[] {
  const samples: Sample[] = [];
  for (let i = 0; i < WARMUP + RUNS; i += 1) {
    const { host, wrapper } = mount();
    try {
      wrapper.innerHTML = lightSvg;
      wrapper.getBBox();
      const t: number[] = [];
      step(wrapper, t);
      if (i >= WARMUP) samples.push({ a: t[1]! - t[0]!, b: t[2]! - t[1]!, c: t[3]! - t[2]!, total: t[3]! - t[0]! });
    } finally {
      host.remove();
    }
  }
  return samples;
}

/** Mutations one switch causes: records, and distinct elements touched. */
function countMutations(lightSvg: string, apply: (wrapper: SVGGElement) => void): { records: number; elements: number; total: number } {
  const { host, wrapper } = mount();
  try {
    wrapper.innerHTML = lightSvg;
    const total = wrapper.getElementsByTagName('*').length;
    const observer = new MutationObserver(() => {});
    observer.observe(wrapper, { attributes: true, childList: true, subtree: true, characterData: true });
    apply(wrapper);
    const records = observer.takeRecords();
    observer.disconnect();
    const touched = new Set<Node>();
    for (const r of records) {
      touched.add(r.target);
      r.addedNodes.forEach((n) => touched.add(n));
    }
    return { records: records.length, elements: touched.size, total };
  } finally {
    host.remove();
  }
}

/** Parse like `innerHTML` does, but detached, for morphdom's target tree. */
function parseDetached(svg: string): Element {
  const scratch = document.createElementNS(SVG_NS, 'g');
  scratch.innerHTML = svg;
  return scratch.firstElementChild!;
}

/** The painted result, for checking a prototype swap is actually correct. */
function paintSnapshot(wrapper: SVGGElement): string {
  const out: string[] = [];
  for (const el of wrapper.querySelectorAll('path, rect, circle, text, marker path, marker circle')) {
    const cs = getComputedStyle(el);
    out.push(`${el.getAttribute('class') ?? ''}:${cs.fill}/${cs.stroke}/${cs.opacity}/${cs.strokeDasharray}`);
  }
  return out.join('\n');
}

function stripPaint(svg: string): string {
  return svg.replace(/<style>[^<]*<\/style>/g, '<style/>').replace(/<defs>.*?<\/defs>/, '<defs/>');
}

const results: string[] = [];

afterAll(() => {
  if (results.length > 0) console.log(`[F9-P1] SUMMARY\n${results.join('\n')}`);
});

function report(variant: string, doc: string, samples: readonly Sample[], extra = ''): void {
  const line =
    `[F9-P1] ${variant} | ${doc} | a ${fmt(samples.map((s) => s.a))} | b ${fmt(samples.map((s) => s.b))}` +
    ` | c ${fmt(samples.map((s) => s.c))} | total ${fmt(samples.map((s) => s.total))}${extra === '' ? '' : ` | ${extra}`}`;
  results.push(line);
  console.log(line);
}

describe.skipIf(IS_FIREFOX)('F9 phase 1: theme switch light -> dark, forced layout, Chromium', () => {
  for (const doc of DOCS) {
    const light = fixture(doc, 'neutral-light');
    const dark = fixture(doc, 'neutral-dark');
    const render = renderMain;

    it(`${doc}: 1 baseline innerHTML`, () => {
      const lightSvg = render(light).svg;
      const samples = bench(lightSvg, (wrapper, t) => {
        t.push(performance.now());
        const r = render(dark);
        t.push(performance.now());
        wrapper.innerHTML = r.svg;
        t.push(performance.now());
        wrapper.getBBox();
        t.push(performance.now());
      });
      const darkSvg = render(dark).svg;
      const m = countMutations(lightSvg, (w) => (w.innerHTML = darkSvg));
      report('1 baseline innerHTML', doc, samples, `mutations ${m.records}, elements touched ${m.elements} of ${m.total}`);
      expect(samples.length).toBe(RUNS);
    });

    it(`${doc}: 2 morphdom (main classes)`, () => {
      const lightSvg = render(light).svg;
      const samples = bench(lightSvg, (wrapper, t) => {
        t.push(performance.now());
        const r = render(dark);
        t.push(performance.now());
        const next = parseDetached(r.svg);
        parseTimes.push(performance.now() - t[1]!);
        morphdom(wrapper.firstElementChild!, next);
        t.push(performance.now());
        wrapper.getBBox();
        t.push(performance.now());
      });
      const parse = parseTimes.splice(0).slice(WARMUP);
      const darkSvg = render(dark).svg;
      const m = countMutations(lightSvg, (w) => morphdom(w.firstElementChild!, parseDetached(darkSvg)));
      report('2 morphdom', doc, samples, `b.parse ${fmt(parse)} | mutations ${m.records}, elements touched ${m.elements} of ${m.total}`);
      // Correctness: the morphed tree paints exactly like a fresh dark render.
      expect(morphedEqualsFresh(lightSvg, darkSvg, (w) => morphdom(w.firstElementChild!, parseDetached(darkSvg)))).toBe(true);
    });

    it(`${doc}: 3a invariant classes, <style>/<defs> swap`, () => {
      const lightInv = renderInvariant(light.styled, light.result, light.theme);
      const darkInv = renderInvariant(dark.styled, dark.result, dark.theme);
      // The prototype's claim: a theme switch changes only the style text and the marker defs.
      expect(stripPaint(lightInv.svg)).toBe(stripPaint(darkInv.svg));
      expect(lightInv.svg).not.toBe(darkInv.svg);
      const swap = (wrapper: SVGGElement, r: { styleBlock: string; tokenBlock: string; defs: string }): void => {
        const root = wrapper.firstElementChild!;
        const styles = root.querySelectorAll(':scope > style');
        styles[0]!.textContent = r.styleBlock;
        styles[1]!.textContent = r.tokenBlock;
        root.querySelector(':scope > defs')!.innerHTML = r.defs;
      };
      const samples = bench(lightInv.svg, (wrapper, t) => {
        t.push(performance.now());
        const r = renderInvariant(dark.styled, dark.result, dark.theme);
        t.push(performance.now());
        swap(wrapper, r);
        t.push(performance.now());
        wrapper.getBBox();
        t.push(performance.now());
      });
      const m = countMutations(lightInv.svg, (w) => swap(w, darkInv));
      report('3a invariant + style swap', doc, samples, `mutations ${m.records}, elements touched ${m.elements} of ${m.total}`);
      expect(morphedEqualsFresh(lightInv.svg, darkInv.svg, (w) => swap(w, darkInv))).toBe(true);

      // 3a': the same swap fed by the paint-only walk, the full string built later.
      const paintOnly = bench(lightInv.svg, (wrapper, t) => {
        t.push(performance.now());
        const r = renderPaintOnly(dark.styled, dark.result, dark.theme);
        t.push(performance.now());
        swap(wrapper, r);
        t.push(performance.now());
        wrapper.getBBox();
        t.push(performance.now());
      });
      const p = renderPaintOnly(dark.styled, dark.result, dark.theme);
      expect(p.styleBlock).toBe(darkInv.styleBlock);
      expect(p.defs).toBe(darkInv.defs);
      report("3a' invariant + style swap, paint-only walk", doc, paintOnly);
    });

    it(`${doc}: 3b invariant classes, morphdom`, () => {
      const lightInv = renderInvariant(light.styled, light.result, light.theme).svg;
      const darkInv = renderInvariant(dark.styled, dark.result, dark.theme).svg;
      const samples = bench(lightInv, (wrapper, t) => {
        t.push(performance.now());
        const r = renderInvariant(dark.styled, dark.result, dark.theme);
        t.push(performance.now());
        const next = parseDetached(r.svg);
        parseTimes.push(performance.now() - t[1]!);
        morphdom(wrapper.firstElementChild!, next);
        t.push(performance.now());
        wrapper.getBBox();
        t.push(performance.now());
      });
      const parse = parseTimes.splice(0).slice(WARMUP);
      const m = countMutations(lightInv, (w) => morphdom(w.firstElementChild!, parseDetached(darkInv)));
      report('3b invariant + morphdom', doc, samples, `b.parse ${fmt(parse)} | mutations ${m.records}, elements touched ${m.elements} of ${m.total}`);
      expect(morphedEqualsFresh(lightInv, darkInv, (w) => morphdom(w.firstElementChild!, parseDetached(darkInv)))).toBe(true);
    });

    it(`${doc}: 1m main classes, memoised class/marker naming, innerHTML`, () => {
      // No output change at all: the memo only stops `render()` recomputing
      // the same class string (BigInt fnv1a64 + declaration building) once
      // per element.
      expect(renderMainProto(dark.styled, dark.result, dark.theme, true).svg).toBe(render(dark).svg);
      expect(renderMainProto(light.styled, light.result, light.theme, true).svg).toBe(render(light).svg);
      const samples = bench(render(light).svg, (wrapper, t) => {
        t.push(performance.now());
        const r = renderMainProto(dark.styled, dark.result, dark.theme, true);
        t.push(performance.now());
        wrapper.innerHTML = r.svg;
        t.push(performance.now());
        wrapper.getBBox();
        t.push(performance.now());
      });
      report('1m main + memo, innerHTML (byte-identical output)', doc, samples);
    });

    it(`${doc}: 3m invariant classes + memo, <style>/<defs> swap, several feeds`, () => {
      const lightInv = renderInvariant(light.styled, light.result, light.theme, true);
      const darkInv = renderInvariant(dark.styled, dark.result, dark.theme, true);
      expect(lightInv.svg).toBe(renderInvariant(light.styled, light.result, light.theme).svg);
      expect(darkInv.svg).toBe(renderInvariant(dark.styled, dark.result, dark.theme).svg);
      const swap = (wrapper: SVGGElement, r: { styleBlock: string; tokenBlock: string; defs: string }): void => {
        const root = wrapper.firstElementChild!;
        const styles = root.querySelectorAll(':scope > style');
        styles[0]!.textContent = r.styleBlock;
        styles[1]!.textContent = r.tokenBlock;
        root.querySelector(':scope > defs')!.innerHTML = r.defs;
      };

      // Full render (the string `lastGood.svg` needs), then the swap; (c) split.
      const styleOnly: number[] = [];
      const full = bench(lightInv.svg, (wrapper, t) => {
        t.push(performance.now());
        const r = renderInvariant(dark.styled, dark.result, dark.theme, true);
        t.push(performance.now());
        swap(wrapper, r);
        t.push(performance.now());
        void getComputedStyle(wrapper.querySelector('text')!).fill; // style recalc only
        styleOnly.push(performance.now() - t[2]!);
        wrapper.getBBox();
        t.push(performance.now());
      });
      report('3m invariant + memo, full render, style swap', doc, full, `c.styleRecalc ${fmt(styleOnly.slice(WARMUP))}`);

      // Paint-only walk: the full string would be built after the frame.
      const paint = bench(lightInv.svg, (wrapper, t) => {
        t.push(performance.now());
        const r = renderPaintOnly(dark.styled, dark.result, dark.theme, true);
        t.push(performance.now());
        swap(wrapper, r);
        t.push(performance.now());
        wrapper.getBBox();
        t.push(performance.now());
      });
      report("3m' invariant + memo, paint-only walk, style swap", doc, paint);

      // As 3m', but getBBox on the canvas rect: same forced style + layout, no tree-wide bbox union.
      const leaf = bench(lightInv.svg, (wrapper, t) => {
        t.push(performance.now());
        const r = renderPaintOnly(dark.styled, dark.result, dark.theme, true);
        t.push(performance.now());
        swap(wrapper, r);
        t.push(performance.now());
        (wrapper.querySelector('rect.canvas') as SVGGraphicsElement).getBBox();
        t.push(performance.now());
      });
      report("3m'' invariant + memo, paint-only walk, style swap, getBBox(rect.canvas)", doc, leaf);

      // CSSOM: rewrite only the rules whose declarations changed, leave the sheet in place.
      const cssom = (wrapper: SVGGElement, r: { styleBlock: string; tokenBlock: string; defs: string }): void => {
        const root = wrapper.firstElementChild!;
        const styles = root.querySelectorAll(':scope > style');
        patchSheet((styles[0] as HTMLStyleElement).sheet!, r.styleBlock);
        patchSheet((styles[1] as HTMLStyleElement).sheet!, r.tokenBlock);
        root.querySelector(':scope > defs')!.innerHTML = r.defs;
      };
      const om = bench(lightInv.svg, (wrapper, t) => {
        t.push(performance.now());
        const r = renderPaintOnly(dark.styled, dark.result, dark.theme, true);
        t.push(performance.now());
        cssom(wrapper, r);
        t.push(performance.now());
        wrapper.getBBox();
        t.push(performance.now());
      });
      report("3m-cssom invariant + memo, paint-only walk, CSSOM rule patch", doc, om);
      expect(morphedEqualsFresh(lightInv.svg, darkInv.svg, (w) => cssom(w, darkInv))).toBe(true);

      // Without the token <style> (F18: removed in the F7/F14 re-baseline).
      // Its `svg.sgl{--…}` rule sets *inherited* custom properties on the root,
      // so changing it restyles every descendant whatever the classes say.
      const noTokens = (svg: string): string => svg.replace(/<style>svg\.sgl\{[^<]*<\/style>/, '');
      const swapNoTokens = (wrapper: SVGGElement, r: { styleBlock: string; defs: string }): void => {
        const root = wrapper.firstElementChild!;
        root.querySelector(':scope > style')!.textContent = r.styleBlock;
        root.querySelector(':scope > defs')!.innerHTML = r.defs;
      };
      expect(noTokens(lightInv.svg)).not.toContain('--sgl-canvas');
      const nt = bench(noTokens(lightInv.svg), (wrapper, t) => {
        t.push(performance.now());
        const r = renderPaintOnly(dark.styled, dark.result, dark.theme, true);
        t.push(performance.now());
        swapNoTokens(wrapper, r);
        t.push(performance.now());
        wrapper.getBBox();
        t.push(performance.now());
      });
      report("3n' invariant + memo, paint-only walk, style swap, NO token block", doc, nt);
      expect(morphedEqualsFresh(noTokens(lightInv.svg), noTokens(darkInv.svg), (w) => swapNoTokens(w, darkInv))).toBe(true);

      const ntFull = bench(noTokens(lightInv.svg), (wrapper, t) => {
        t.push(performance.now());
        const r = renderInvariant(dark.styled, dark.result, dark.theme, true);
        t.push(performance.now());
        swapNoTokens(wrapper, r);
        t.push(performance.now());
        wrapper.getBBox();
        t.push(performance.now());
      });
      report('3n invariant + memo, full render, style swap, NO token block', doc, ntFull);

      // ...and with the one type selector (`text{white-space:pre}`) scoped to
      // classes, in case a type selector widens Chromium's invalidation.
      const TYPE_RULE = 'text{white-space:pre}';
      const CLASS_RULE = '.n-title,.c-title,.el-text{white-space:pre}';
      const scoped = (s: string): string => s.replace(TYPE_RULE, CLASS_RULE);
      expect(lightInv.svg).toContain(TYPE_RULE);
      const ntScoped = bench(scoped(noTokens(lightInv.svg)), (wrapper, t) => {
        t.push(performance.now());
        const r = renderPaintOnly(dark.styled, dark.result, dark.theme, true);
        t.push(performance.now());
        swapNoTokens(wrapper, { styleBlock: scoped(r.styleBlock), defs: r.defs });
        t.push(performance.now());
        wrapper.getBBox();
        t.push(performance.now());
      });
      report("3s' invariant + memo, paint-only walk, style swap, NO token block, no type selector", doc, ntScoped);

      // Control for the above: the same swap on main's token-less output via
      // innerHTML, to size what dropping the token block alone buys on main.
      const mainNt = bench(noTokens(render(light).svg), (wrapper, t) => {
        t.push(performance.now());
        const r = renderMainProto(dark.styled, dark.result, dark.theme, true);
        t.push(performance.now());
        wrapper.innerHTML = noTokens(r.svg);
        t.push(performance.now());
        wrapper.getBBox();
        t.push(performance.now());
      });
      report('1n main + memo, innerHTML, NO token block', doc, mainNt);
    });

    it(`${doc}: 5 control: no change at all, getBBox(wrapper)`, () => {
      const samples = bench(render(light).svg, (wrapper, t) => {
        t.push(performance.now());
        t.push(performance.now());
        t.push(performance.now());
        wrapper.getBBox();
        t.push(performance.now());
      });
      report('5 control: clean tree, getBBox(wrapper) only', doc, samples);
    });

    it(`${doc}: 4a main classes, getBBox on a leaf instead of the wrapper`, () => {
      // Does *which* element getBBox is asked for matter? (It should not: the
      // style + layout update it forces is document-wide.)
      const lightSvg = render(light).svg;
      const samples = bench(lightSvg, (wrapper, t) => {
        t.push(performance.now());
        const r = render(dark);
        t.push(performance.now());
        wrapper.innerHTML = r.svg;
        t.push(performance.now());
        (wrapper.querySelector('rect.canvas') as SVGGraphicsElement).getBBox();
        t.push(performance.now());
      });
      report('4a innerHTML, getBBox(rect.canvas)', doc, samples);
    });

    it(`${doc}: 4b render() alone vs string build share`, () => {
      // Split (a): how much of render() is the paint walk and how much is the
      // element strings. Reported as a = render(), b = renderPaintOnly(), c = 0.
      const samples: Sample[] = [];
      for (let i = 0; i < WARMUP + RUNS; i += 1) {
        const t0 = performance.now();
        render(dark);
        const t1 = performance.now();
        renderPaintOnly(dark.styled, dark.result, dark.theme);
        const t2 = performance.now();
        if (i >= WARMUP) samples.push({ a: t1 - t0, b: t2 - t1, c: 0, total: t2 - t0 });
      }
      report('4b a=render() b=paint-only walk (not a switch)', doc, samples);

      const memo: Sample[] = [];
      for (let i = 0; i < WARMUP + RUNS; i += 1) {
        const t0 = performance.now();
        renderMainProto(dark.styled, dark.result, dark.theme, true);
        const t1 = performance.now();
        renderInvariant(dark.styled, dark.result, dark.theme, true);
        const t2 = performance.now();
        renderPaintOnly(dark.styled, dark.result, dark.theme, true);
        const t3 = performance.now();
        if (i >= WARMUP) memo.push({ a: t1 - t0, b: t2 - t1, c: t3 - t2, total: t3 - t0 });
      }
      report('4c a=main+memo b=invariant+memo c=paint-only+memo (not a switch)', doc, memo);

      // Upstream of the bench's timed region, but on a real theme switch's
      // path (DD-08 §3): `styleGraph` re-runs for the new theme and hashes
      // every element's bags with the BigInt `fnv1a64`.
      const sg: number[] = [];
      for (let i = 0; i < WARMUP + RUNS; i += 1) {
        const t0 = performance.now();
        const out = styleGraph(dark.styled.graph, dark.theme);
        const t1 = performance.now();
        if (i >= WARMUP) sg.push(t1 - t0);
        if (i === 0) expect(out.value.paintHash).toBe(dark.styled.paintHash);
      }
      results.push(`[F9-P1] 4d styleGraph() alone (not in the F9 timed region) | ${doc} | ${fmt(sg)}`);

      // How much of that is the hash: the strings styleGraph hashes, through
      // core's BigInt fnv1a64 and through the limb prototype (same output).
      const inputs: string[] = [];
      for (const s of [...Object.values(dark.styled.styles), ...Object.values(dark.styled.labelStyles)] as ComputedStyle[]) {
        inputs.push(canonicalise(s.geometry), canonicalise({ ...s.geometry, ...s.paint }));
      }
      for (const probe of ['', 'a', 'héllo wörld', '日本語', '😀 emoji', '\ud800 lone', ...inputs.slice(0, 50)]) {
        expect(fnv1a64Fast(probe)).toBe(fnv1a64(probe));
      }
      const slow: number[] = [];
      const fast: number[] = [];
      for (let i = 0; i < WARMUP + RUNS; i += 1) {
        const t0 = performance.now();
        for (const s of inputs) fnv1a64(s);
        const t1 = performance.now();
        for (const s of inputs) fnv1a64Fast(s);
        const t2 = performance.now();
        if (i >= WARMUP) {
          slow.push(t1 - t0);
          fast.push(t2 - t1);
        }
      }
      results.push(`[F9-P1] 4e ${inputs.length} per-element hashes of styleGraph | ${doc} | BigInt fnv1a64 ${fmt(slow)} | limb fnv1a64 ${fmt(fast)}`);
    });
  }
});

const parseTimes: number[] = [];

/** Apply `text` (one rule per line, as `buildStyleBlock` emits) to `sheet`
 *  rule by rule, touching only rules whose declarations changed. */
function patchSheet(sheet: CSSStyleSheet, text: string): void {
  const next = new Map<string, string>();
  for (const line of text.split('\n')) {
    const open = line.indexOf('{');
    next.set(line.slice(0, open), line.slice(open + 1, -1));
  }
  const rules = sheet.cssRules;
  for (let i = 0; i < rules.length; i += 1) {
    const rule = rules[i] as CSSStyleRule;
    const decls = next.get(rule.selectorText.replace(/, /g, ','));
    if (decls === undefined) continue;
    const probe = document.createElement('div').style;
    probe.cssText = decls;
    if (probe.cssText !== rule.style.cssText) rule.style.cssText = decls;
  }
}

function renderMain(f: Fixture): ReturnType<typeof render> {
  return render(f.styled, f.result, f.theme);
}

/** After `apply` on a mounted `fromSvg`, does it paint like a fresh `toSvg`? */
function morphedEqualsFresh(fromSvg: string, toSvg: string, apply: (wrapper: SVGGElement) => void): boolean {
  const a = mount();
  const b = mount();
  try {
    a.wrapper.innerHTML = fromSvg;
    apply(a.wrapper);
    b.wrapper.innerHTML = toSvg;
    const sa = paintSnapshot(a.wrapper);
    const sb = paintSnapshot(b.wrapper);
    const same = sa === sb && a.wrapper.innerHTML.length > 0;
    if (!same) {
      const la = sa.split('\n');
      const lb = sb.split('\n');
      const i = la.findIndex((l, k) => l !== lb[k]);
      console.log(`[F9-P1] paint mismatch at ${i}: ${la[i]} vs ${lb[i]}`);
    }
    return same;
  } finally {
    a.host.remove();
    b.host.remove();
  }
}
