import { afterEach, describe, expect, it } from 'vitest';
import type { LayoutView } from '../../src/layout-view.js';
import { render } from '../../src/index.js';
// @ts-expect-error -- generated by bench/generate-render-fixtures.js (gitignored;
// `pnpm generate:bench-fixtures` writes it before this project runs), not a
// source file this package ships or type-checks against.
import fixtures from '../../../../bench/render-fixtures.json';

/**
 * F7 (DD-07 §6): a marker's colour is not in its id or its `<defs>` markup but
 * a `<style>` rule on its own shape's class (`mf-{token}` filled, `ms-{token}`
 * stroked for `open`). This holds Chromium to it: every arrowhead is painted
 * the colour of the edge it ends, under both themes, for every kind. (Inkscape
 * 1.2.2 and resvg were checked by hand when this landed; see the execution
 * plan's §2 entry for the re-baseline.)
 */

interface Fixture {
  readonly doc: string;
  readonly themeName: string;
  readonly styled: Parameters<typeof render>[0];
  readonly result: LayoutView;
  readonly theme: Parameters<typeof render>[2];
}

const FIXTURES = (fixtures as readonly Fixture[]).filter((f) => f.doc === 'n50.sgl');

function mount(svgText: string): SVGSVGElement {
  const parsed = new DOMParser().parseFromString(svgText, 'image/svg+xml');
  expect(parsed.querySelector('parsererror')).toBeNull();
  const svg = document.importNode(parsed.documentElement, true) as unknown as SVGSVGElement;
  document.body.append(svg);
  return svg;
}

afterEach(() => {
  document.body.replaceChildren();
});

/** `styled` with every edge's arrowhead set to `kind`. */
function withArrowhead(styled: Fixture['styled'], kind: string): Fixture['styled'] {
  const styles = Object.fromEntries(
    Object.entries(styled.styles).map(([id, s]) => [id, 'arrowhead' in s.paint ? { ...s, paint: { ...s.paint, arrowhead: kind } } : s]),
  );
  return { ...styled, styles: styles as typeof styled.styles };
}

describe('F7: arrowheads are painted by a class rule, in Chromium (DD-07 §6)', () => {
  it('has the n50 fixtures under both themes', () => {
    expect(FIXTURES.map((f) => f.themeName).sort()).toEqual(['neutral-dark', 'neutral-light']);
  });

  for (const { themeName, styled, result, theme } of FIXTURES) {
    for (const kind of ['triangle', 'open', 'diamond', 'circle'] as const) {
      it(`n50 / ${themeName} / ${kind}: every marker is its edge's stroke colour`, () => {
        const svg = mount(render(withArrowhead(styled, kind), result, theme).svg);
        const edges = [...svg.querySelectorAll('path.e-path[marker-end]')] as SVGPathElement[];
        expect(edges.length).toBeGreaterThan(0);
        for (const edge of edges) {
          const id = /^url\(#(.+)\)$/.exec(edge.getAttribute('marker-end')!)![1]!;
          expect(id.startsWith(`m-${kind}-`)).toBe(true);
          const shape = svg.getElementById(id)!.firstElementChild as SVGGraphicsElement;
          const want = getComputedStyle(edge).stroke;
          expect(want).not.toBe('none');
          if (kind === 'open') {
            expect(getComputedStyle(shape).stroke).toBe(want);
            expect(getComputedStyle(shape).fill).toBe('none');
          } else {
            expect(getComputedStyle(shape).fill).toBe(want);
          }
        }
      });
    }
  }
});
