import type { LayoutView } from '../../src/layout-view.js';
import { render } from '../../src/index.js';
import { afterEach, describe, expect, it } from 'vitest';
// @ts-expect-error -- generated by bench/generate-render-fixtures.js (gitignored;
// `pnpm generate:bench-fixtures` writes it before this project runs), not a
// source file this package ships or type-checks against.
import fixtures from '../../../../bench/render-fixtures.json';

/**
 * F17/F18 (execution plan §2.1, DD-07 §6): the rendered file has one `<style>`
 * element, which paints the whole diagram with literal values and declares no
 * custom property (the theme-token element F17 split out was removed with
 * F18). This checks, in a real CSS engine, that the element is CSS a browser
 * accepts whole, that it declares no custom property, and that the canvas is
 * painted by its literal colour.
 */

interface Fixture {
  readonly doc: string;
  readonly themeName: string;
  readonly styled: Parameters<typeof render>[0];
  readonly result: LayoutView;
  readonly theme: Parameters<typeof render>[2];
}

const FIXTURES = (fixtures as readonly Fixture[]).filter((f) => f.doc === 'n50.sgl');

/** Attach the rendered file to this page's document as standalone SVG, the
 *  way a docs site inlines an exported `.svg`. */
function mount(svgText: string): SVGSVGElement {
  const parsed = new DOMParser().parseFromString(svgText, 'image/svg+xml');
  expect(parsed.querySelector('parsererror')).toBeNull();
  const svg = document.importNode(parsed.documentElement, true) as unknown as SVGSVGElement;
  document.body.append(svg);
  return svg;
}

/** A colour as the CSS engine computes it, for comparison with `fill`. */
function computedColor(value: string): string {
  const probe = document.createElement('span');
  probe.style.color = value;
  document.body.append(probe);
  const out = getComputedStyle(probe).color;
  probe.remove();
  return out;
}

afterEach(() => {
  document.body.replaceChildren();
});

describe('F17/F18: the one <style> element (DD-07 §6)', () => {
  it('has the n50 fixtures under both themes', () => {
    expect(FIXTURES.map((f) => f.themeName).sort()).toEqual(['neutral-dark', 'neutral-light']);
  });

  for (const { themeName, styled, result, theme } of FIXTURES) {
    it(`n50 / ${themeName}: one <style>, every rule kept, no custom property, the canvas literal`, () => {
      const rendered = render(styled, result, theme);
      const svg = mount(rendered.svg);
      const styles = [...svg.querySelectorAll('style')];
      expect(styles).toHaveLength(1);
      const sheet = styles[0]!.sheet;
      expect(sheet).not.toBeNull();

      // The browser kept every rule the renderer wrote (a malformed one would
      // be dropped), and none of them declares a custom property.
      const written = rendered.styleBlock.split('\n').filter((l) => l !== '');
      expect(sheet!.cssRules).toHaveLength(written.length);
      for (const rule of [...sheet!.cssRules] as CSSStyleRule[]) {
        expect([...rule.style].filter((p) => p.startsWith('--')), rule.selectorText).toEqual([]);
      }

      // The canvas is painted by the element's literal colour.
      const canvas = svg.querySelector('rect.canvas') as SVGRectElement;
      expect(getComputedStyle(canvas).fill).toBe(computedColor(styled.canvas.background));
      const shape = svg.querySelector('.n-shape') as SVGPathElement;
      expect(getComputedStyle(shape).fill).not.toBe('rgb(0, 0, 0)');
    });
  }
});
