import type { LayoutView } from '../../src/layout-view.js';
import { render } from '../../src/index.js';
import { afterEach, describe, expect, it } from 'vitest';
// @ts-expect-error -- generated by bench/generate-render-fixtures.js (gitignored;
// `pnpm generate:bench-fixtures` writes it before this project runs), not a
// source file this package ships or type-checks against.
import fixtures from '../../../../bench/render-fixtures.json';

/**
 * F17 (execution plan §2.1, DD-07 §6): the theme tokens moved out of the main
 * `<style>` into an element of their own, and `.canvas` now carries a literal
 * colour. This checks, in a real CSS engine, that the move kept DD-07's
 * re-theme promise: the token element is CSS a browser accepts whole — one
 * `svg.sgl` rule whose every declaration survives parsing — the diagram is
 * painted by the main element alone, and a consumer's own `svg.sgl{--…}` rule
 * overrides a token on the exported root.
 */

interface Fixture {
  readonly doc: string;
  readonly themeName: string;
  readonly styled: Parameters<typeof render>[0];
  readonly result: LayoutView;
  readonly theme: Parameters<typeof render>[2];
}

const FIXTURES = (fixtures as readonly Fixture[]).filter((f) => f.doc === 'n50.sgl');

/** Attach the rendered file to this page's document as standalone SVG, the
 *  way a docs site inlines an exported `.svg`. */
function mount(svgText: string): SVGSVGElement {
  const parsed = new DOMParser().parseFromString(svgText, 'image/svg+xml');
  expect(parsed.querySelector('parsererror')).toBeNull();
  const svg = document.importNode(parsed.documentElement, true) as unknown as SVGSVGElement;
  document.body.append(svg);
  return svg;
}

/** A colour as the CSS engine computes it, for comparison with `fill`. */
function computedColor(value: string): string {
  const probe = document.createElement('span');
  probe.style.color = value;
  document.body.append(probe);
  const out = getComputedStyle(probe).color;
  probe.remove();
  return out;
}

afterEach(() => {
  document.body.replaceChildren();
});

describe('F17: the separate token <style> keeps the re-theme promise (DD-07 §6)', () => {
  it('has the n50 fixtures under both themes', () => {
    expect(FIXTURES.map((f) => f.themeName).sort()).toEqual(['neutral-dark', 'neutral-light']);
  });

  for (const { themeName, styled, result, theme } of FIXTURES) {
    it(`n50 / ${themeName}: tokens parse whole, the canvas is literal, and a consumer override wins`, () => {
      const rendered = render(styled, result, theme);
      const svg = mount(rendered.svg);
      const styles = [...svg.querySelectorAll('style')];
      expect(styles).toHaveLength(2);
      const [, tokenElement] = styles as [HTMLStyleElement, HTMLStyleElement];

      // The token element is one rule, `svg.sgl`, and the browser kept every
      // declaration the renderer wrote (a malformed one would be dropped).
      const sheet = tokenElement.sheet;
      expect(sheet).not.toBeNull();
      expect(sheet!.cssRules).toHaveLength(1);
      const rule = sheet!.cssRules[0] as CSSStyleRule;
      expect(rule.selectorText).toBe('svg.sgl');
      const written = rendered.tokenBlock.slice('svg.sgl{'.length, -1).split(';');
      const kept = [...rule.style].filter((p) => p.startsWith('--'));
      expect(kept.length).toBe(written.length);
      expect([...rule.style].filter((p) => !p.startsWith('--'))).toEqual([]);

      // The canvas is painted by the main element's literal colour, the same
      // value the `--sgl-canvas` token carries.
      const canvasToken = getComputedStyle(svg).getPropertyValue('--sgl-canvas').trim();
      expect(canvasToken).not.toBe('');
      const canvas = svg.querySelector('rect.canvas') as SVGRectElement;
      expect(getComputedStyle(canvas).fill).toBe(computedColor(canvasToken));

      // Removing the token element — what a tool that rejects custom
      // properties does — leaves the diagram's paint untouched.
      const shape = svg.querySelector('.n-shape') as SVGPathElement;
      const before = { canvas: getComputedStyle(canvas).fill, shape: getComputedStyle(shape).fill };
      tokenElement.remove();
      expect({ canvas: getComputedStyle(canvas).fill, shape: getComputedStyle(shape).fill }).toEqual(before);
      svg.querySelector('style')!.after(tokenElement);

      // A consumer's override of a token applies to the exported root.
      const override = document.createElementNS('http://www.w3.org/2000/svg', 'style');
      override.textContent = 'svg.sgl{--ink:#123456;--sgl-canvas:#654321}';
      svg.append(override);
      expect(getComputedStyle(svg).getPropertyValue('--ink').trim()).toBe('#123456');
      expect(getComputedStyle(svg).getPropertyValue('--sgl-canvas').trim()).toBe('#654321');
    });
  }
});
